navbar is created
Web-Dev-Rich/tlydp pull request #2
Opened 2022-01-25 09:20 UTC by muhsinaltintop

Nav bar is created without any style customization ability.

2022-01-25 16:32 UTC, al-anan submitted a review, later dismissed

2022-01-27 12:11 UTC, aakirahin approved these changes

2022-01-27 12:22 UTC, al-anan requested changes
it looks like the branch has conflicts as per message above that need solving before merging

2022-01-27 13:43 UTC, al-anan approved these changes
approved and merged

2022-01-27 13:43 UTC, merged