Added registration form with labels
Web-Dev-Rich/tlydp pull request #3
Opened 2022-01-25 14:37 UTC by aakirahin

2022-01-25 16:50 UTC, al-anan requested changes

2022-01-25 16:50 UTC, al-anan commented on pubspec.lock
> +<<<<<<< HEAD
unresolved conflict, one version needs to be chosen

2022-01-25 16:50 UTC, al-anan commented on lib/registration.dart/registration_page.dart
> +                  return "Passwords should have at least one uppercase and lowercase letter, one number and one special character";
error message too long, does not appear in full when mobile page is in vertical position (looks fine when in horizontal position)

2022-01-25 16:50 UTC, al-anan commented on lib/screens/landing_screen.dart
> +            child: AppButton(text: 'Create an account'),
needs to have a route to Register screen

2022-01-26 10:06 UTC, aakirahin commented on pubspec.lock
> +<<<<<<< HEAD
0.4.3 is the one we want I think

2022-01-26 10:06 UTC, aakirahin commented on lib/screens/landing_screen.dart
> +            child: AppButton(text: 'Create an account'),
added

2022-01-28 10:05 UTC, al-anan approved these changes

2022-01-28 10:06 UTC, merged